site_name: 'CiviCRM Benutzerhandbuch'
site_url: https://docs.civicrm.org/user/de/stable/
repo_url: https://github.com/grince/civicrm-user-guide-de
site_description: 'Ein Handbuch für CiviCRM Nutzer.'
site_author: 'Die CiviCRM Bewegung'
theme: material
markdown_extensions:
  - attr_list
  - admonition
  - def_list
  - codehilite(guess_lang=false)
  - toc(permalink=true)
  - pymdownx.superfences
  - pymdownx.inlinehilite
  - pymdownx.tilde
  - pymdownx.betterem
  - pymdownx.mark

pages:
- Home: 'index.md' (untranslated)
- Introduction: (untranslated)
    - 'What is CiviCRM?': 'introduction/what-is-civicrm.md' (untranslated)
    - 'Is CiviCRM for You?': 'introduction/is-civicrm-for-you.md' (untranslated)
    - 'Real World Examples': 'introduction/real-world-examples.md' (untranslated)
    - 'Components': 'introduction/components.md' (untranslated)
    - 'Extensions': 'introduction/extensions.md' (untranslated)
    - 'Who is CiviCRM?': 'introduction/who-is-civicrm.md' (untranslated)
- Initial set up: (untranslated)
    - 'Installation and basic set-up': 'initial-set-up/installation-and-basic-set-up.md' (untranslated)
    - 'Customizing the user interface': 'initial-set-up/customizing-the-user-interface.md' (untranslated)
    - 'Dates': 'initial-set-up/dates.md' (untranslated)
    - 'Addresses': 'initial-set-up/addresses.md' (untranslated)
    - 'Mapping': 'initial-set-up/mapping.md' (untranslated)
    - 'Users contacts': 'initial-set-up/users-contacts.md' (untranslated)
    - 'Permissions and access control': 'initial-set-up/permissions-and-access-control.md' (untranslated)
    - 'Resource urls': 'initial-set-up/resource-urls.md' (untranslated)
    - 'Logging': 'initial-set-up/change-logging.md' (untranslated)
    - 'Error handling': 'initial-set-up/error-handling.md' (untranslated)
    - 'Scheduled Jobs': 'initial-set-up/scheduled-jobs.md' (untranslated)
- The user interface: (untranslated)
    - 'Menu, dashboard and dashlets': 'the-user-interface/menu-dashboard-and-dashlets.md' (untranslated)
    - 'Searching': 'the-user-interface/searching.md' (untranslated)
    - 'Undelete': 'the-user-interface/undelete.md' (untranslated)
- Organising your data: (untranslated)
    - 'Overview': 'organising-your-data/overview.md' (untranslated)
    - 'Mapping your data': 'organising-your-data/mapping-your-data.md' (untranslated)
    - 'Contacts': 'organising-your-data/contacts.md' (untranslated)
    - 'Groups and tags': 'organising-your-data/groups-and-tags.md' (untranslated)
    - 'Smart groups': 'organising-your-data/smart-groups.md' (untranslated)
    - 'Activities': 'organising-your-data/activities.md' (untranslated)
    - 'Relationships': 'organising-your-data/relationships.md' (untranslated)
    - 'Creating Custom Fields': 'organising-your-data/creating-custom-fields.md' (untranslated)
    - 'Profiles': 'organising-your-data/profiles.md' (untranslated)
- Common workflows: (untranslated)
    - 'Importing Data into CiviCRM': 'common-workflows/importing-data-into-civicrm.md' (untranslated)
    - 'Exporting Your Contacts': 'common-workflows/exporting-your-contacts.md' (untranslated)
    - 'Deduping and Merging': 'common-workflows/deduping-and-merging.md' (untranslated)
    - 'Tokens and mail merge': 'common-workflows/tokens-and-mail-merge.md' (untranslated)
    - 'Postal mail communications': 'common-workflows/postal-mail-communications.md' (untranslated)
    - 'Automating tasks': 'common-workflows/automating-tasks.md' (untranslated)
- Contributions: (untranslated)
    - 'What is CiviContribute?': 'contributions/what-is-civicontribute.md' (untranslated)
    - 'Key concepts and configurations': 'contributions/key-concepts-and-configurations.md' (untranslated)
    - 'Online contributions': 'contributions/online-contributions.md' (untranslated)
    - 'Offline fundraising': 'contributions/offline-fundraising.md' (untranslated)
    - 'Manual entry of contributions': 'contributions/manual-entry-of-contributions.md' (untranslated)
    - 'Finding and viewing contributions': 'contributions/finding-and-viewing-contributions.md' (untranslated)
    - 'Manual receipts and thank-you letters': 'contributions/manual-receipts-and-thank-yous.md' (untranslated)
    - 'Reports and analysis': 'contributions/reports-and-analysis.md' (untranslated)
    - 'Soft credits': 'contributions/soft-credits.md' (untranslated)
    - 'Personal Campaign Pages': 'contributions/personal-campaign-pages.md' (untranslated)
    - 'Accounting Integration': 'contributions/accounting-integration.md' (untranslated)
    - 'Payment processors': 'contributions/payment-processors.md' (untranslated)
    - 'Invoicing': 'contributions/invoicing.md' (untranslated)
    - 'Sales tax and VAT': 'contributions/sales-tax-and-vat.md' (untranslated)
    - 'Premiums': 'contributions/premiums.md' (untranslated)
    - 'Widgets': 'contributions/widgets.md' (untranslated)
- Pledges: (untranslated)
    - 'What is CiviPledge?': 'pledges/what-is-civipledge.md' (untranslated)
    - 'What you need to know': 'pledges/what-you-need-to-know.md' (untranslated)
    - 'Set-up': 'pledges/set-up.md' (untranslated)
    - 'Everyday tasks': 'pledges/everyday-tasks.md' (untranslated)
    - 'Pledges Reports and Analysis': 'pledges/pledges-reports-and-analysis.md' (untranslated)
- Events: (untranslated)
    - 'What is CiviEvent?': 'events/what-is-civievent.md' (untranslated)
    - 'Event planning and management': 'events/event-planning-and-management.md' (untranslated)
    - 'Creating an event': 'events/creating-an-event.md' (untranslated)
    - 'Online event registration': 'events/online-event-registration.md' (untranslated)
    - 'Integrating events with your website': 'events/integrating-events-with-your-website.md' (untranslated)
    - 'Manual event registration': 'events/manual-event-registration.md' (untranslated)
    - 'Keeping track of events and participants': 'events/keeping-track-of-events-and-participants.md' (untranslated)
    - 'Complex event fees': 'events/complex-event-fees.md' (untranslated)
    - 'Event templates': 'events/event-templates.md' (untranslated)
    - 'Reports': 'events/reports.md' (untranslated)
    - 'Custom data for events': 'events/custom-data-for-events.md' (untranslated)
    - 'Repeating Events': 'events/repeating-events.md' (untranslated)
- Membership: (untranslated)
    - 'What is CiviMember': 'membership/what-is-civimember.md' (untranslated)
    - 'Defining memberships': 'membership/defining-memberships.md' (untranslated)
    - 'Online membership sign up': 'membership/online-membership-sign-up.md' (untranslated)
    - 'Manual entry of memberships': 'membership/manual-entry-of-memberships.md' (untranslated)
    - 'Membership price sets': 'membership/membership-price-sets.md' (untranslated)
    - 'Finding and viewing memberships': 'membership/finding-and-viewing-memberships.md' (untranslated)
    - 'Membership Reports': 'membership/membership-reports.md' (untranslated)
    - 'Renewals': 'membership/renewals.md' (untranslated)
    - 'Cancelling and expiring memberships': 'membership/cancelling-and-expiring-memberships.md' (untranslated)
    - 'Making member only websites': 'membership/making-member-only-websites.md' (untranslated)
- Email: (untranslated)
    - 'What is CiviMail?': 'email/what-is-civimail.md' (untranslated)
    - 'What You Need To Know': 'email/what-you-need-to-know.md' (untranslated)
    - 'Set-up': 'email/set-up.md' (untranslated)
    - 'Maintaining Healthy Email Lists': 'email/maintaining-healthy-email-lists.md' (untranslated)
    - 'Everyday tasks': 'email/everyday-tasks.md' (untranslated)
    - 'Mass mailings using CiviMail': 'email/mass-mailings-using-civimail.md' (untranslated)
    - 'Reports and analysis': 'email/reports-and-analysis.md' (untranslated)
    - 'Scheduled reminders': 'email/scheduled-reminders.md' (untranslated)
    - 'CiviMail A/B Testing': 'email/civimail-ab-testing.md' (untranslated)
    - 'Message templates': 'email/message-templates.md' (untranslated)
- SMS (text messaging): (untranslated)
    - 'What is SMS?': 'sms-text-messaging/what-is-sms.md' (untranslated)
    - 'Set-up': 'sms-text-messaging/set-up.md' (untranslated)
    - 'Everyday tasks': 'sms-text-messaging/everyday-tasks.md' (untranslated)
    - 'Reports and Analysis (SMS)': 'sms-text-messaging/reports-and-analysis-sms.md' (untranslated)
- Reporting: (untranslated)
    - 'What is CiviReport?': 'reporting/what-is-civireport.md' (untranslated)
    - 'What You Need To Know': 'reporting/what-you-need-to-know.md' (untranslated)
    - 'Set-up': 'reporting/set-up.md' (untranslated)
    - 'Everyday Tasks': 'reporting/everyday-tasks.md' (untranslated)
- Case management: (untranslated)
    - 'What is CiviCase?': 'case-management/what-is-civicase.md' (untranslated)
    - 'What You Need To Know': 'case-management/what-you-need-to-know.md' (untranslated)
    - 'Set-up': 'case-management/set-up.md' (untranslated)
    - 'Everyday Tasks': 'case-management/everyday-tasks.md' (untranslated)
    - 'Reports and analysis': 'case-management/reports-and-analysis.md' (untranslated)
- Campaign: (untranslated)
    - 'What is CiviCampaign?': 'campaign/what-is-civicampaign.md' (untranslated)
    - 'What You Need To Know': 'campaign/what-you-need-to-know.md' (untranslated)
    - 'Set-up': 'campaign/set-up.md' (untranslated)
    - 'Everyday tasks': 'campaign/everyday-tasks.md' (untranslated)
    - 'Reports and analysis': 'campaign/reports-and-analysis.md' (untranslated)
- Survey: (untranslated)
    - 'What is CiviSurvey?': 'survey/what-is-civisurvey.md' (untranslated)
    - 'What You Need To Know': 'survey/what-you-need-to-know.md' (untranslated)
    - 'Set-up': 'survey/set-up.md' (untranslated)
    - 'Everyday Tasks': 'survey/everyday-tasks.md' (untranslated)
    - 'Reports and analysis': 'survey/reports-and-analysis.md' (untranslated)
    - 'What is GOTV (Voter Tracking)?': 'survey/what-is-gotv-voter-tracking.md' (untranslated)
- Petition: (untranslated)
    - 'What is CiviPetition?': 'petition/what-is-civipetition.md' (untranslated)
    - 'What You Need To Know': 'petition/what-you-need-to-know.md' (untranslated)
    - 'Set-up': 'petition/set-up.md' (untranslated)
    - 'Everyday Tasks': 'petition/everyday-tasks.md' (untranslated)
    - 'Reports and analysis': 'petition/reports-and-analysis.md' (untranslated)
- Civic Engagement: (untranslated)
    - 'What is CiviEngage?': 'civic-engagement/what-is-civiengage.md' (untranslated)
    - 'What You Need To Know': 'civic-engagement/what-you-need-to-know.md' (untranslated)
    - 'Set-up': 'civic-engagement/set-up.md' (untranslated)
    - 'Everyday Tasks': 'civic-engagement/everyday-tasks.md' (untranslated)
    - 'Reports and analysis': 'civic-engagement/reports-and-analysis.md' (untranslated)
- Grants: (untranslated)
    - 'What is CiviGrant?': 'grants/what-is-civigrant.md' (untranslated)
    - 'What You Need To Know': 'grants/what-you-need-to-know.md' (untranslated)
    - 'Set-up': 'grants/set-up.md' (untranslated)
    - 'Everyday tasks': 'grants/every-day-tasks.md' (untranslated)
    - 'Reports and analysis': 'grants/reports-and-analysis.md' (untranslated)
- The CiviCRM Community: (untranslated)
    - 'The CiviCRM Community': 'the-civicrm-community/the-civicrm-community.md' (untranslated)
    - 'Bug Reporting': 'the-civicrm-community/bug-reporting.md' (untranslated)
    - 'Localising CiviCRM': 'the-civicrm-community/localising-civicrm.md' (untranslated)
    - 'Contributing to this guide': 'the-civicrm-community/contributing-to-this-manual.md' (untranslated)
- Appendices: (untranslated)
    - 'History of this book': 'appendices/history-of-this-book.md' (untranslated)
    - 'Free Software?': 'appendices/free-software.md' (translated)
    - 'Glossary': 'appendices/glossary.md' (partially translated)
    - 'Credits': 'appendices/credits.md' (translated)
